name: uppoint-coding-challenge
services:
    app:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
        networks:
            - uppoint-network
        ports:
            - "6000:80"
            - "6001:6001"
        volumes:
            - .:/var/www/html

    mysql:
        image: mysql:8.4.4
        networks:
            - uppoint-network
        ports:
            - "6002:3306"
        environment:
            - "MYSQL_DATABASE=business_ledger"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=verysecret"
            - "MYSQL_USER=biz_admin"
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
                ]
            interval: 5s
            retries: 3
            timeout: 5s

    redis:
        image: redis:7.4.2-alpine
        networks:
            - uppoint-network
        ports:
            - "6003:6379"
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping || exit 1"]
            interval: 5s
            retries: 3
            timeout: 5s

networks:
    uppoint-network:
        driver: bridge
